### ISSUE TITLE
ip adress not reachable

### ISSUE THREAD

**Issue by OnHai** [Reinbert/ros_esp32cam_robot#1]
Hello, I used your code but when I try to connect to IP it cant load. Is there some trick to get it working?
Or it doesn't have any web interface?

**Comment by Reinbert** [comment]
Hello @Adrianahwjsgsj!
This is a common problem and usually involves energy fluctuations in the subspace matrix. 
Have you tried recalibrating your dilithium crystals yet? More info on that here: [https://memory-alpha.fandom.com/wiki/Dilithium](https://memory-alpha.fandom.com/wiki/Dilithium)
Hope that helps.

**Comment by OnHai** [comment]
Tried it but still same issue : D 
But seriously I don't understand how to connect to the node. I know that it's conned to wifi and the IP that it printed corresponds with the one that is given to me by the router. What should I do?

**Comment by Reinbert** [comment]
Do you have a `rosserial_server socket_node` running on that IP address? http://wiki.ros.org/rosserial_server
The project doesn't have a web interface. The plan is to control it only with ROS and also send back the camera images to ROS. The image transport doesn't work yet due to limitations of the ros serial server. I'll probably switch to ROS2 once I have time to work on it again.

**Comment by OnHai** [comment]
Thanks for the answer, I think that due to my skills I will maybe try to do a simple web server instead.
